services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - space
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx:ro
      - ${NGINX_DATA_PATH}:/usr/share/nginx:ro

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: default
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d:ro
    ports:
      - "3306:3306"
    networks:
      - space

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_CONF_PATH}:/usr/local/etc/redis/:ro
      - ${REDIS_DATA_PATH}:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - space

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
      - ${RABBITMQ_CONF_PATH}:/etc/rabbitmq:ro
    networks:
      - space
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db
    networks:
      - space

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${ES_DATA_PATH}:/usr/share/elasticsearch/data
    networks:
      - space


networks:
  space:
    driver: bridge
